backend:
  name: git-gateway
  branch: build

media_folder: "src/images"
public_folder: "/static"

collections:
  - name: 'images'
    label: 'Image'
    folder: 'src/images'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Media', name: 'media', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image'}